# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate Variance Inflation Factor
#' @description Calculate Variance Inflation Factor (VIF) for each predictor variable in a dataset.
#' @param x A numeric matrix of predictor variables (independent variables).
#' @return A numeric vector of VIF values for each predictor variable in the dataset.
#' @examples
#' \dontrun{
#' data(mtcars)
#' vif(as.matrix(mtcars[, -1]))
#' }
#' @export
vif <- function(x) {
    .Call(`_SA24204137_vif`, x)
}

rcpp_hello_world <- function() {
    .Call(`_SA24204137_rcpp_hello_world`)
}

